name: besprotoritsa_app
description: Flutter user interface for Besprotoritsa.
publish_to: none

environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  besprotoritsa_data:
    path: ../besprotoritsa_data
  besprotoritsa_rules:
    path: ../besprotoritsa_rules
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.0
