name: besprotoritsa_rules
description: Pure Dart game rules for Besprotoritsa.
publish_to: none

environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  collection: ^1.19.1
  meta: ^1.19.0

dev_dependencies:
  test: ^1.25.15
  very_good_analysis: ^9.0.0
