// The generator consumes JSON catalogs whose nested shapes are validated in CI.
// ignore_for_file: avoid_dynamic_calls, cast_nullable_to_non_nullable

import 'dart:convert';
import 'dart:io';

const _directories = [
  'characters',
  'conditions',
  'events',
  'hexes',
  'items',
  'monsters',
  'quests',
];

Future<void> main() async {
  final content = <String, Object?>{};
  for (final name in _directories) {
    final directory = Directory('content/mvp/$name');
    final files = await directory
        .list()
        .where((entry) => entry is File && entry.path.endsWith('.json'))
        .cast<File>()
        .toList();
    files.sort((a, b) => a.path.compareTo(b.path));
    content[name] = [
      for (final file in files)
        jsonDecode(await file.readAsString()) as Map<String, Object?>,
    ];
  }
  content['layout'] = jsonDecode(
    await File('content/mvp/layout.json').readAsString(),
  );
  final catalog =
      jsonDecode(
            await File('content/characters.json').readAsString(),
          )
          as Map<String, Object?>;
  content['catalogCharacters'] = catalog['characters'];
  content['decks'] = jsonDecode(
    await File('content/mvp/decks.json').readAsString(),
  );
  final encoded = jsonEncode(content).replaceAll(r'$', r'\$');
  final output = File(
    'packages/besprotoritsa_app/lib/src/game/mvp_runtime_content.g.dart',
  );
  await output.writeAsString(
    '// Generated by `dart run tool/generate_mvp_runtime.dart`.\n'
    '// Source of truth: content/mvp/*.json.\n'
    '// ignore_for_file: lines_longer_than_80_chars\n'
    '/// Embedded, checked JSON snapshot of the deterministic MVP runtime set.\n'
    "const mvpRuntimeContentJson = '$encoded';\n",
  );
  final full = <String, Object?>{};
  for (final name in [
    'characters',
    'conditions',
    'events',
    'hexes',
    'items',
    'monsters',
    'quests',
    'special_items',
    'supplies',
    'tasks',
  ]) {
    full[name] = jsonDecode(await File('content/$name.json').readAsString());
  }
  full['decks'] = <String, Object?>{
    'conditions': [
      for (final card in (full['conditions'] as Map)['cards'] as List)
        for (var copy = 0; copy < (card['copies'] as int? ?? 1); copy++)
          card['id'],
    ],
    'events': [
      for (final card in (full['events'] as Map)['cards'] as List)
        for (var copy = 0; copy < (card['copies'] as int? ?? 1); copy++)
          card['id'],
    ],
    'storyQuests': (full['quests'] as Map)['initialQuestIds'],
  };
  final translations =
      jsonDecode(
            await File('content/i18n/ru.json').readAsString(),
          )
          as Map<String, dynamic>;
  full['contentTranslations'] = _flattenTranslations(
    translations['content'],
    'content',
  );
  full['characterNames'] =
      (translations['content'] as Map<String, dynamic>)['character'];
  final fullEncoded = jsonEncode(full);
  await File(
    'packages/besprotoritsa_app/lib/src/game/full_runtime_content.g.dart',
  ).writeAsString(
    '// Generated by `dart run tool/generate_mvp_runtime.dart`.\n'
    '// Source of truth: checked top-level content catalogs.\n'
    '// ignore_for_file: lines_longer_than_80_chars\n'
    '// ignore_for_file: avoid_escaping_inner_quotes, prefer_single_quotes\n'
    '/// Embedded snapshot of the validated full content set.\n'
    'const fullRuntimeContentJson = '
    '${jsonEncode(fullEncoded.replaceAll(r'$', r'\$'))};\n',
  );
}

Map<String, String> _flattenTranslations(Object? value, String prefix) {
  if (value is! Map<String, dynamic>) return const {};
  final flattened = <String, String>{};
  for (final entry in value.entries) {
    final key = '$prefix.${entry.key}';
    if (entry.value is String) {
      flattened[key] = entry.value as String;
    } else {
      flattened.addAll(_flattenTranslations(entry.value, key));
    }
  }
  return flattened;
}
