import 'dart:convert';
import 'dart:io';

const _directories = [
  'characters',
  'conditions',
  'events',
  'hexes',
  'items',
  'monsters',
  'quests',
];

Future<void> main() async {
  final content = <String, Object?>{};
  for (final name in _directories) {
    final directory = Directory('content/mvp/$name');
    final files = await directory
        .list()
        .where((entry) => entry is File && entry.path.endsWith('.json'))
        .cast<File>()
        .toList();
    files.sort((a, b) => a.path.compareTo(b.path));
    content[name] = [
      for (final file in files)
        jsonDecode(await file.readAsString()) as Map<String, Object?>,
    ];
  }
  content['layout'] = jsonDecode(
    await File('content/mvp/layout.json').readAsString(),
  );
  final catalog =
      jsonDecode(
            await File('content/characters.json').readAsString(),
          )
          as Map<String, Object?>;
  content['catalogCharacters'] = catalog['characters'];
  content['decks'] = jsonDecode(
    await File('content/mvp/decks.json').readAsString(),
  );
  final encoded = jsonEncode(content).replaceAll(r'$', r'\$');
  final output = File(
    'packages/besprotoritsa_app/lib/src/game/mvp_runtime_content.g.dart',
  );
  await output.writeAsString(
    '// Generated by `dart run tool/generate_mvp_runtime.dart`.\n'
    '// Source of truth: content/mvp/*.json.\n'
    '// ignore_for_file: lines_longer_than_80_chars\n'
    '/// Embedded, checked JSON snapshot of the deterministic MVP runtime set.\n'
    "const mvpRuntimeContentJson = '$encoded';\n",
  );
}
